Labange.PL/Models/Company/CompanyCreateModel.cs
using Labange.DAL.Entities;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Labange.PL.Models.Company
{
    public class CompanyCreateModel
    {
        [Required]
        [StringLength(50, ErrorMessage = "Name cannot be longer than 50 characters.")]
        public string Name { get; set; }
        [Required]
        [StringLength(50, ErrorMessage = "City cannot be longer than 50 characters.")]
        public string City { get; set; }
        [Required]
        [Range(0, 500000)]
        public int Quantity { get; set; }
        public string About { get; set; }
        [Required]
        [Display(Name = "Area of business")]
        public BusinessArea BusinessArea { get; set; }
    }
}

Labange.PL/Models/Company/CompanyDetailsModel.cs
using Labange.DAL.Entities;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Labange.PL.Models.Company
{
    public class CompanyDetailsModel
    {
        public int Id { get; set; }
        [Required]
        [StringLength(50, ErrorMessage = "First name cannot be longer than 50 characters.")]
        public string Name { get; set; }
        [Required]
        [StringLength(50, ErrorMessage = "City cannot be longer than 50 characters.")]
        public string City { get; set; }
        [Required]
        [Range(0, 500000)]
        public int Quantity { get; set; }
        public string About { get; set; }
        [Required]
        [Display(Name = "Area of business")]
        public BusinessArea BusinessArea { get; set; }
    }
}

Labange.PL/Models/Company/CompanyListItemModel.cs
using Labange.DAL.Entities;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Labange.PL.Models.Company
{
    public class CompanyListItemModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string City { get; set; }
        public int Quantity { get; set; }
        [Display(Name = "Area of business")]
        public BusinessArea BusinessArea { get; set; }
    }
}

Labange.PL/Controllers/CompaniesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Labange.BLL.Interfaces;
using AutoMapper;
using Labange.PL.Infrastructure.Mappers;
using Labange.PL.Models.Company;
using Labange.BLL.DTO.Company;

namespace Labange.PL.Controllers
{
    public class CompaniesController : Controller
    {
        private const string SortNameDesc = "name_desc";
        private const string SortCityAsc = "city_asc";
        private const string SortCityDesc = "city_desc";
        private const string SortQuantityAsc = "quantiy_asc";
        private const string SortQuantityDesc = "quantity_desc";

        private readonly ICompanyService _companyService;
        private readonly IMapper _mapper;
        
        public CompaniesController(ICompanyService companyService)
        {
            _companyService = companyService;
            _mapper = new MapperConfiguration(x => x.AddProfile(new CompanyMapperProfile())).CreateMapper();
        }

        // GET: Companies
        public async Task<IActionResult> Index(string sortOrder)
        {
            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? SortNameDesc : "";
            ViewData["CitySortParm"] = sortOrder == SortCityAsc ? SortCityDesc : SortCityAsc;
            ViewData["QuantitySortParm"] = sortOrder == SortQuantityAsc ? SortQuantityDesc : SortQuantityAsc;

            IEnumerable<CompanyListItemDto> companiesDto = await _companyService.GetAllCompaniesAsync();
            var companies = _mapper.Map<IEnumerable<CompanyListItemDto>, IEnumerable<CompanyListItemModel>>(companiesDto);

            switch (sortOrder)
            {
                case SortNameDesc:
                    companies = companies.OrderByDescending(c => c.Name);
                    break;
                case SortCityAsc:
                    companies = companies.OrderBy(c => c.City);
                    break;
                case SortCityDesc:
                    companies = companies.OrderByDescending(c => c.City);
                    break;
                case SortQuantityAsc:
                    companies = companies.OrderBy(c => c.Quantity);
                    break;
                case SortQuantityDesc:
                    companies = companies.OrderByDescending(c => c.Quantity);
                    break;
                default:
                    companies = companies.OrderBy(c => c.Name);
                    break;
            }

            return View(companies);
        }

        // GET: Companies/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            CompanyDetailsDto companyDto = await _companyService.GetCompanyAsync((int)id);
            var company = _mapper.Map<CompanyDetailsDto, CompanyDetailsModel>(companyDto);

            if (company == null)
            {
                return NotFound();
            }
            return View(company);
        }

        // GET: Companies/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Companies/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,City,Quantity,About,BusinessArea")] CompanyCreateModel companyModel)
        {
            if (ModelState.IsValid)
            {
                var company = _mapper.Map<CompanyCreateModel, CompanyCreateDto>(companyModel);
                await _companyService.CreateCompanyAsync(company);
                return RedirectToAction(nameof(Index));
            }

            return View(companyModel);
        }

        // GET: Companies/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            CompanyDetailsDto companyDto = await _companyService.GetCompanyAsync((int)id);
            var company = _mapper.Map<CompanyDetailsDto, CompanyDetailsModel>(companyDto);

            if (company == null)
            {
                return NotFound();
            }
            return View(company);
        }

        // POST: Companies/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,City,Quantity,About,BusinessArea")] CompanyDetailsModel companyModel)
        {
            if (id != companyModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                var company = _mapper.Map<CompanyDetailsModel, CompanyDetailsDto>(companyModel);
                await _companyService.UpdateCompanyAsync(company);
                return RedirectToAction(nameof(Index));
            }
            return View(companyModel);
        }

        // GET: Companies/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            CompanyDetailsDto companyDto = await _companyService.GetCompanyAsync((int)id);
            if (companyDto == null)
            {
                return NotFound();
            }
            var company = _mapper.Map<CompanyDetailsDto, CompanyDetailsModel>(companyDto);
            return View(company);
        }

        // POST: Companies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _companyService.DeleteCompanyAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Labange.PL/Controllers/VacationsController.cs
using AutoMapper;
using Labange.BLL.DTO.Vacation;
using Labange.BLL.Interfaces;
using Labange.PL.Infrastructure.Mappers;
using Labange.PL.Models.Vacation;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Labange.PL.Controllers
{
    public class VacationsController : Controller
    {
        private const string SortNameDesc = "name_desc";
        private const string SortSalaryAsc = "salary_asc";
        private const string SortSalaryDesc = "salary_desc";
        private const string SortCompanyNameAsc = "companyName_asc";
        private const string SortCompanyNameDesc = "companyName_desc";

        private readonly IVacationService _vacationService;
        private readonly IMapper _mapper;

        public VacationsController(IVacationService vacationService)
        {
            _vacationService = vacationService;
            _mapper = new MapperConfiguration(x => x.AddProfile(new VacationMapperProfile())).CreateMapper();
        }

        public async Task<IActionResult> Index(string sortOrder, string searchString)
        {
            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? SortNameDesc : "";
            ViewData["SalarySortParm"] = sortOrder == SortSalaryAsc ? SortSalaryDesc : SortSalaryAsc;
            ViewData["CompanyNameSortParm"] = sortOrder == SortCompanyNameAsc ? SortCompanyNameDesc : SortCompanyNameAsc;

            ViewData["SearchFilter"] = searchString;

            IEnumerable<VacationListItemDto> vacationsDto = await _vacationService.GetAllVacationsAsync(searchString);
            var vacations = _mapper.Map<IEnumerable<VacationListItemDto>, IEnumerable<VacationListItemModel>>(vacationsDto);

            switch (sortOrder)
            {
                case SortNameDesc:
                    vacations = vacations.OrderByDescending(v => v.Name);
                    break;
                case SortSalaryAsc:
                    vacations = vacations.OrderBy(v => v.Salary);
                    break;
                case SortSalaryDesc:
                    vacations = vacations.OrderByDescending(v => v.Salary);
                    break;
                case SortCompanyNameAsc:
                    vacations = vacations.OrderBy(v => v.CompanyName);
                    break;
                case SortCompanyNameDesc:
                    vacations = vacations.OrderByDescending(v => v.CompanyName);
                    break;
                default:
                    vacations = vacations.OrderBy(v => v.Name);
                    break;
            }

            return View(vacations);
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            VacationDetailsDto vacationDto = await _vacationService.GetVacationAsync((int)id);
            var vacation = _mapper.Map<VacationDetailsDto, VacationDetailsModel>(vacationDto);
            if (vacation == null)
            {
                return NotFound();
            }
            return View(vacation);
        }

        public IActionResult Create(int id)
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(int id, [Bind("Name,Salary,Responsibilities,SkillCategory")] VacationCreateModel vacationModel)
        {
            if (ModelState.IsValid)
            {
                vacationModel.CompanyId = id;
                var vacation = _mapper.Map<VacationCreateModel, VacationCreateDto>(vacationModel);
                await _vacationService.CreateVacationAsync(vacation);
                return RedirectToAction(nameof(Index));
            }

            return View(vacationModel);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            VacationDetailsDto vacationDto = await _vacationService.GetVacationAsync((int)id);
            var vacation = _mapper.Map<VacationDetailsDto, VacationDetailsModel>(vacationDto);

            if (vacation == null)
            {
                return NotFound();
            }
            return View(vacation);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Salary,Responsibilities,SkillCategory")] VacationDetailsModel vacationModel)
        {
            if (id != vacationModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                var vacation = _mapper.Map<VacationDetailsModel, VacationDetailsDto>(vacationModel);
                await _vacationService.UpdateVacationAsync(vacation);
                return RedirectToAction(nameof(Index));
            }
            return View(vacationModel);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            VacationDetailsDto vacationDto = await _vacationService.GetVacationAsync((int)id);
            if (vacationDto == null)
            {
                return NotFound();
            }
            var vacation = _mapper.Map<VacationDetailsDto, VacationDetailsModel>(vacationDto);
            return View(vacation);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _vacationService.DeleteVacationAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Labange.PL/Views/Companies/Create.cshtml
@model Labange.PL.Models.Company.CompanyCreateModel
@using Labange.DAL.Entities;

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Company</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="About" class="control-label"></label>
                <textarea asp-for="About" class="form-control" rows="8">
                </textarea>
                <span asp-validation-for="About" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BusinessArea" class="control-label"></label>
                <select asp-for="BusinessArea" class="form-control" asp-items="@Html.GetEnumSelectList<BusinessArea>()">
                    <option value="">-- Select Business Area --</option>
                </select>
                <span asp-validation-for="BusinessArea" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>


Labange.PL/Views/Companies/Delete.cshtml
@model Labange.PL.Models.Company.CompanyDetailsModel

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Company</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>
        <dt>
            
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Quantity)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.About)
        </dt>
        <dd>
            <pre>@Html.DisplayFor(model => model.About)</pre>
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.BusinessArea)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.BusinessArea)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Labange.PL/Views/Companies/Details.cshtml
@model Labange.PL.Models.Company.CompanyDetailsModel

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Company</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Quantity)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.About)
        </dt>
        <dd>
            <pre>@Html.DisplayFor(model => model.About)</pre>
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.BusinessArea)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.BusinessArea)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Labange.PL/Views/Companies/Edit.cshtml
@model Labange.PL.Models.Company.CompanyDetailsModel
@using Labange.DAL.Entities;

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Company</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="About" class="control-label"></label>
                <textarea asp-for="About" class="form-control" rows="8">
                </textarea>
                <span asp-validation-for="About" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BusinessArea" class="control-label"></label>
                <select asp-for="BusinessArea" class="form-control" asp-items="@Html.GetEnumSelectList<BusinessArea>()">
                    <option value="">-- Select Business Area --</option>
                </select>
                <span asp-validation-for="BusinessArea" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>


Labange.PL/Views/Companies/Index.cshtml
@model IEnumerable<Labange.PL.Models.Company.CompanyListItemModel>

@{
    ViewData["Title"] = "Index";
}

<h2>Companies</h2>

<p class="create-button">
    <a asp-action="Create"> 
        <input type="submit" value="Create New" class="btn btn-default" />
    </a>
</p>
<table class="table">
    <thead>
        <tr>
                <th>
                    <a asp-action="Index" asp-route-sortOrder="@ViewData["NameSortParm"]">@Html.DisplayNameFor(model => model.Name)</a>
                </th>
                <th>
                    <a asp-action="Index" asp-route-sortOrder="@ViewData["CitySortParm"]">@Html.DisplayNameFor(model => model.City)</a>
                </th>
                <th>
                    <a asp-action="Index" asp-route-sortOrder="@ViewData["QuantitySortParm"]">@Html.DisplayNameFor(model => model.Quantity)</a>
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.BusinessArea)
                </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.City)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Quantity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BusinessArea)
            </td>
            <td>
                <a asp-controller="Vacations" asp-action="Create" asp-route-id="@item.Id">Add Vacation</a> |
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>