Labange.PL/Models/Resume/ResumeCreateModel.cs
using Labange.DAL.Entities;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Labange.PL.Models.Resume
{
    public class ResumeCreateModel
    {
        [Required]
        public string About { get; set; }
        [Required]
        [Range(0, 60)]
        [Display(Name = "Years of Experience")]
        public int ExperienceYears { get; set; }
        [Required]
        public string Skills { get; set; }
        [Display(Name = "Previous places of work")]
        public string PlacesOfWork { get; set; }
        [Required]
        [Display(Name = "Category")]
        public SkillCategory SkillCategory { get; set; }
        public int UnemployedId { get; set; }
    }
}

Labange.PL/Models/Resume/ResumeDetailsModel.cs
using Labange.DAL.Entities;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Labange.PL.Models.Resume
{
    public class ResumeDetailsModel
    {
        public int Id { get; set; }
        [Required]
        public string About { get; set; }
        [Required]
        [Range(0, 60)]
        [Display(Name = "Years of Experience")]
        public int ExperienceYears { get; set; }
        [Required]
        public string Skills { get; set; }
        [Display(Name = "Previous places of work")]
        public string PlacesOfWork { get; set; }
        [Display(Name = "Category")]
        public SkillCategory SkillCategory { get; set; }
        public int UnemployedId { get; set; }
        public string Name { get; set; }
    }
}

Labange.PL/Models/Resume/ResumeListitemModel.cs
using Labange.DAL.Entities;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Labange.PL.Models.Resume
{
    public class ResumeListItemModel
    {
        public int Id { get; set; }
        [Display(Name = "Years of Experience")]
        public int ExperienceYears { get; set; }
        [Display(Name = "Category")]
        public SkillCategory SkillCategory { get; set; }
        public string Name { get; set; }
        public int UnemployedId { get; set; }
    }
}

Labange.PL/Controllers/ResumesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Labange.BLL.DTO.Resume;
using Labange.BLL.Interfaces;
using Labange.PL.Infrastructure.Mappers;
using Labange.PL.Models.Resume;
using Microsoft.AspNetCore.Mvc;

namespace Labange.PL.Controllers
{
    public class ResumesController : Controller
    {
        private const string SortNameDesc = "name_desc";
        private const string SortExperienceYearsAsc = "experienceYears_asc";
        private const string SortExperienceYearsDesc = "experienceYears_desc";
        private const string SortSkillCategoryAsc = "skillCategory_asc";
        private const string SortSkillCategoryDesc = "skillCategory_desc";

        private readonly IResumeService _resumeService;
        private readonly IMapper _mapper;

        public ResumesController(IResumeService resumeService)
        {
            _resumeService = resumeService;
            _mapper = new MapperConfiguration(x => x.AddProfile(new ResumeMapperProfile())).CreateMapper();
        }

        public async Task<IActionResult> Index(string sortOrder)
        {
            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? SortNameDesc : "";
            ViewData["ExperienceYearsSortParm"] = sortOrder == SortExperienceYearsAsc ? SortExperienceYearsDesc : SortExperienceYearsAsc;
            ViewData["SkillCategorySortParm"] = sortOrder == SortSkillCategoryAsc ? SortSkillCategoryDesc : SortSkillCategoryAsc;

            IEnumerable<ResumeListItemDto> resumesDto = await _resumeService.GetAllResumesAsync();
            var resumes = _mapper.Map<IEnumerable<ResumeListItemDto>, IEnumerable<ResumeListItemModel>>(resumesDto);

            switch (sortOrder)
            {
                case SortNameDesc:
                    resumes = resumes.OrderByDescending(r => r.Name);
                    break;
                case SortExperienceYearsAsc:
                    resumes = resumes.OrderBy(r => r.ExperienceYears);
                    break;
                case SortExperienceYearsDesc:
                    resumes = resumes.OrderByDescending(r => r.ExperienceYears);
                    break;
                case SortSkillCategoryAsc:
                    resumes = resumes.OrderBy(r => r.SkillCategory);
                    break;
                case SortSkillCategoryDesc:
                    resumes = resumes.OrderByDescending(r => r.SkillCategory);
                    break;
                default:
                    resumes = resumes.OrderBy(r => r.Name);
                    break;
            }

            return View(resumes);
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            ResumeDetailsDto resumeDto = await _resumeService.GetResumeAsync((int)id);
            var resume = _mapper.Map<ResumeDetailsDto, ResumeDetailsModel>(resumeDto);
            if (resume == null)
            {
                return NotFound();
            }
            return View(resume);
        }

        public async Task<IActionResult> Create(int id)
        {
            bool isExist = await _resumeService.IsExistAsync(id);
            if (isExist)
                return Redirect($"~/Resumes/Details/{id}");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(int id, [Bind("About,ExperienceYears,Skills,PlacesOfWork,SkillCategory")] ResumeCreateModel resumeModel)
        {
            if (ModelState.IsValid)
            {
                resumeModel.UnemployedId = id;
                var resume = _mapper.Map<ResumeCreateModel, ResumeCreateDto>(resumeModel);
                await _resumeService.CreateResumeAsync(resume);
                return RedirectToAction(nameof(Index));
            }

            return View(resumeModel);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            ResumeDetailsDto resumeDto = await _resumeService.GetResumeAsync((int)id);
            var resume = _mapper.Map<ResumeDetailsDto, ResumeDetailsModel>(resumeDto);

            if (resume == null)
            {
                return NotFound();
            }
            return View(resume);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,About,ExperienceYears,Skills,PlacesOfWork,SkillCategory")] ResumeDetailsModel resumeModel)
        {
            if (id != resumeModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                var resume = _mapper.Map<ResumeDetailsModel, ResumeDetailsDto>(resumeModel);
                await _resumeService.UpdateResumeAsync(resume);
                return RedirectToAction(nameof(Index));
            }
            return View(resumeModel);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            ResumeDetailsDto resumeDto = await _resumeService.GetResumeAsync((int)id);
            if (resumeDto == null)
            {
                return NotFound();
            }
            var resume = _mapper.Map<ResumeDetailsDto, ResumeDetailsModel>(resumeDto);
            return View(resume);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _resumeService.DeleteResumeAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Labange.PL/Controllers/UnemployedsController.cs
using AutoMapper;
using Labange.BLL.DTO.Unemployed;
using Labange.PL.Infrastructure.Mappers;
using Labange.BLL.Interfaces;
using Labange.PL.Models.Unemployed;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Labange.PL.Controllers
{
    public class UnemployedsController : Controller
    {
        private const string SortLastNameDesc = "lastName_desc";
        private const string SortFirstNameAsc = "firstName_asc";
        private const string SortFirstNameDesc = "firstName_desc";
        private const string SortBirthdayAsc = "birthday_asc";
        private const string SortBirthdayDesc = "birthday_desc";
        private const string SortCityAsc = "city_asc";
        private const string SortCityDesc = "city_desc";

        private readonly IUnemployedService _unemployedService;
        private readonly IMapper _mapper;

        public UnemployedsController(IUnemployedService unemployedService)
        {
            _unemployedService = unemployedService;
            _mapper = new MapperConfiguration(x => x.AddProfile(new UnemployedMapperProfile())).CreateMapper();
        }

        public async Task<IActionResult> Index(string sortOrder, string searchString)
        {
            ViewData["LastNameSortParm"] = String.IsNullOrEmpty(sortOrder) ? SortLastNameDesc : "";
            ViewData["FirstNameSortParm"] = sortOrder == SortFirstNameAsc ? SortFirstNameDesc : SortFirstNameAsc;
            ViewData["BirthdaySortParm"] = sortOrder == SortBirthdayAsc ? SortBirthdayDesc : SortBirthdayAsc;
            ViewData["CitySortParm"] = sortOrder == SortCityAsc ? SortCityDesc : SortCityAsc;

            ViewData["SearchFilter"] = searchString;

            IEnumerable<UnemployedDto> unemployedsDto = await _unemployedService.GetAllUnemployedsAsync(searchString);
            var unemployeds = _mapper.Map<IEnumerable<UnemployedDto>, IEnumerable<UnemployedModel>>(unemployedsDto);

            switch (sortOrder)
            {
                case SortLastNameDesc:
                    unemployeds = unemployeds.OrderByDescending(u => u.LastName);
                    break;
                case SortFirstNameAsc:
                    unemployeds = unemployeds.OrderBy(u => u.FirstName);
                    break;
                case SortFirstNameDesc:
                    unemployeds = unemployeds.OrderByDescending(u => u.FirstName);
                    break;
                case SortBirthdayAsc:
                    unemployeds = unemployeds.OrderBy(u => u.Birthday);
                    break;
                case SortBirthdayDesc:
                    unemployeds = unemployeds.OrderByDescending(u => u.Birthday);
                    break;
                case SortCityAsc:
                    unemployeds = unemployeds.OrderBy(u => u.City);
                    break;
                case SortCityDesc:
                    unemployeds = unemployeds.OrderByDescending(u => u.City);
                    break;
                default:
                    unemployeds = unemployeds.OrderBy(u => u.LastName);
                    break;
            }

            return View(unemployeds);
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            UnemployedDto unemployedDto = await _unemployedService.GetUnemployedAsync((int)id);
            var unemployed = _mapper.Map<UnemployedDto, UnemployedModel>(unemployedDto);
            if (unemployed == null)
            {
                return NotFound();
            }
            return View(unemployed);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("FirstName,LastName,City,Birthday")] UnemployedCreateModel unemployedModel)
        {
            if (ModelState.IsValid)
            {
                var unemployed = _mapper.Map<UnemployedCreateModel, UnemployedCreateDto>(unemployedModel);
                await _unemployedService.CreateUnemployedAsync(unemployed);
                return RedirectToAction(nameof(Index));
            }

            return View(unemployedModel);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            UnemployedDto unemployedDto = await _unemployedService.GetUnemployedAsync((int)id);
            var unemployed = _mapper.Map<UnemployedDto, UnemployedCreateModel>(unemployedDto);

            if (unemployed == null)
            {
                return NotFound();
            }
            return View(unemployed);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("FirstName,LastName,City,Birthday")] UnemployedCreateModel unemployedModel)
        {
            if (ModelState.IsValid)
            {
                var unemployed = _mapper.Map<UnemployedCreateModel, UnemployedCreateDto>(unemployedModel);
                await _unemployedService.UpdateUnemployedAsync(id, unemployed);
                return RedirectToAction(nameof(Index));
            }
            return View(unemployedModel);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            UnemployedDto unemployedDto = await _unemployedService.GetUnemployedAsync((int)id);
            if (unemployedDto == null)
            {
                return NotFound();
            }
            var unemployed = _mapper.Map<UnemployedDto, UnemployedModel>(unemployedDto);
            return View(unemployed);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _unemployedService.DeleteUnemployedAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Labange.PL/Views/Resumes/Create.cshtml
@model Labange.PL.Models.Resume.ResumeCreateModel
@using Labange.DAL.Entities;

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Resume</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="About" class="control-label"></label>
                <textarea asp-for="About" class="form-control" rows="4">
                </textarea>
                <span asp-validation-for="About" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ExperienceYears" class="control-label"></label>
                <input asp-for="ExperienceYears" class="form-control" />
                <span asp-validation-for="ExperienceYears" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Skills" class="control-label"></label>
                <textarea asp-for="Skills" class="form-control" rows="5">
                </textarea>
                <span asp-validation-for="Skills" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PlacesOfWork" class="control-label"></label>
                <textarea asp-for="PlacesOfWork" class="form-control" rows="5">
                </textarea>
                <span asp-validation-for="PlacesOfWork" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SkillCategory" class="control-label"></label>
                <select asp-for="SkillCategory" class="form-control" asp-items="@Html.GetEnumSelectList<SkillCategory>()">
                    <option value="">-- Select Category of Skills--</option>
                </select>
                <span asp-validation-for="SkillCategory" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>


Labange.PL/Views/Resumes/Delete.cshtml
@model Labange.PL.Models.Resume.ResumeDetailsModel

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Resume</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            <a asp-controller="Unemployeds" asp-action="Details" asp-route-id="@Model.UnemployedId">@Html.DisplayFor(model => model.Name)</a>
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.About)
        </dt>
        <dd>
            <pre>@Html.DisplayFor(model => model.About)</pre>
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ExperienceYears)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ExperienceYears)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Skills)
        </dt>
        <dd>
            <pre>@Html.DisplayFor(model => model.Skills)</pre>
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PlacesOfWork)
        </dt>
        <dd>
            <pre>@Html.DisplayFor(model => model.PlacesOfWork)</pre>
        </dd>
        <dd>
            @Html.DisplayFor(model => model.SkillCategory)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SkillCategory)
        </dt>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Labange.PL/Views/Resumes/Details.cshtml
@model Labange.PL.Models.Resume.ResumeDetailsModel

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Resume</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            <a asp-controller="Unemployeds" asp-action="Details" asp-route-id="@Model.UnemployedId">@Html.DisplayFor(model => model.Name)</a>
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.About)
        </dt>
        <dd>
            <pre>@Html.DisplayFor(model => model.About)</pre>
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ExperienceYears)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ExperienceYears)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Skills)
        </dt>
        <dd>
            <pre>@Html.DisplayFor(model => model.Skills)</pre>
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PlacesOfWork)
        </dt>
        <dd>
            <pre>@Html.DisplayFor(model => model.PlacesOfWork)</pre>
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SkillCategory)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SkillCategory)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Labange.PL/Views/Resumes/Edit.cshtml
@model Labange.PL.Models.Resume.ResumeDetailsModel
@using Labange.DAL.Entities;

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Resume</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="About" class="control-label"></label>
                <textarea asp-for="About" class="form-control" rows="4">
                </textarea>
                <span asp-validation-for="About" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ExperienceYears" class="control-label"></label>
                <input asp-for="ExperienceYears" class="form-control" />
                <span asp-validation-for="ExperienceYears" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Skills" class="control-label"></label>
                <textarea asp-for="Skills" class="form-control" rows="5">
                </textarea>
                <span asp-validation-for="Skills" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PlacesOfWork" class="control-label"></label>
                <textarea asp-for="PlacesOfWork" class="form-control" rows="5">
                </textarea>
                <span asp-validation-for="PlacesOfWork" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SkillCategory" class="control-label"></label>
                <select asp-for="SkillCategory" class="form-control" asp-items="@Html.GetEnumSelectList<SkillCategory>()">
                    <option value="">-- Select Category of Skills--</option>
                </select>
                <span asp-validation-for="SkillCategory" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>


Labange.PL/Views/Resumes/Index.cshtml
@model IEnumerable<Labange.PL.Models.Resume.ResumeListItemModel>

@{
    ViewData["Title"] = "Index";
}

<h2>Resumes</h2>

<table class="table">
    <thead>
        <tr>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["NameSortParm"]">@Html.DisplayNameFor(model => model.Name)</a>
            </th>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["ExperienceYearsSortParm"]">@Html.DisplayNameFor(model => model.ExperienceYears)</a>
            </th>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["SkillCategorySortParm"]">@Html.DisplayNameFor(model => model.SkillCategory)</a>
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <a asp-controller="Unemployeds" asp-action="Details" asp-route-id="@item.UnemployedId">@Html.DisplayFor(modelItem => item.Name)</a>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ExperienceYears)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SkillCategory)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>