Labange.PL/Controllers/CompaniesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Labange.BLL.Interfaces;
using AutoMapper;
using Labange.PL.Infrastructure.Mappers;
using Labange.PL.Models.Company;
using Labange.BLL.DTO.Company;

namespace Labange.PL.Controllers
{
    public class CompaniesController : Controller
    {
        private const string SortNameDesc = "name_desc";
        private const string SortCityAsc = "city_asc";
        private const string SortCityDesc = "city_desc";
        private const string SortQuantityAsc = "quantiy_asc";
        private const string SortQuantityDesc = "quantity_desc";

        private readonly ICompanyService _companyService;
        private readonly IMapper _mapper;
        
        public CompaniesController(ICompanyService companyService)
        {
            _companyService = companyService;
            _mapper = new MapperConfiguration(x => x.AddProfile(new CompanyMapperProfile())).CreateMapper();
        }

        // GET: Companies
        public async Task<IActionResult> Index(string sortOrder)
        {
            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? SortNameDesc : "";
            ViewData["CitySortParm"] = sortOrder == SortCityAsc ? SortCityDesc : SortCityAsc;
            ViewData["QuantitySortParm"] = sortOrder == SortQuantityAsc ? SortQuantityDesc : SortQuantityAsc;

            IEnumerable<CompanyListItemDto> companiesDto = await _companyService.GetAllCompaniesAsync();
            var companies = _mapper.Map<IEnumerable<CompanyListItemDto>, IEnumerable<CompanyListItemModel>>(companiesDto);

            switch (sortOrder)
            {
                case SortNameDesc:
                    companies = companies.OrderByDescending(c => c.Name);
                    break;
                case SortCityAsc:
                    companies = companies.OrderBy(c => c.City);
                    break;
                case SortCityDesc:
                    companies = companies.OrderByDescending(c => c.City);
                    break;
                case SortQuantityAsc:
                    companies = companies.OrderBy(c => c.Quantity);
                    break;
                case SortQuantityDesc:
                    companies = companies.OrderByDescending(c => c.Quantity);
                    break;
                default:
                    companies = companies.OrderBy(c => c.Name);
                    break;
            }

            return View(companies);
        }

        // GET: Companies/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            CompanyDetailsDto companyDto = await _companyService.GetCompanyAsync((int)id);
            var company = _mapper.Map<CompanyDetailsDto, CompanyDetailsModel>(companyDto);

            if (company == null)
            {
                return NotFound();
            }
            return View(company);
        }

        // GET: Companies/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Companies/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,City,Quantity,About,BusinessArea")] CompanyCreateModel companyModel)
        {
            if (ModelState.IsValid)
            {
                var company = _mapper.Map<CompanyCreateModel, CompanyCreateDto>(companyModel);
                await _companyService.CreateCompanyAsync(company);
                return RedirectToAction(nameof(Index));
            }

            return View(companyModel);
        }

        // GET: Companies/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            CompanyDetailsDto companyDto = await _companyService.GetCompanyAsync((int)id);
            var company = _mapper.Map<CompanyDetailsDto, CompanyDetailsModel>(companyDto);

            if (company == null)
            {
                return NotFound();
            }
            return View(company);
        }

        // POST: Companies/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,City,Quantity,About,BusinessArea")] CompanyDetailsModel companyModel)
        {
            if (id != companyModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                var company = _mapper.Map<CompanyDetailsModel, CompanyDetailsDto>(companyModel);
                await _companyService.UpdateCompanyAsync(company);
                return RedirectToAction(nameof(Index));
            }
            return View(companyModel);
        }

        // GET: Companies/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            CompanyDetailsDto companyDto = await _companyService.GetCompanyAsync((int)id);
            if (companyDto == null)
            {
                return NotFound();
            }
            var company = _mapper.Map<CompanyDetailsDto, CompanyDetailsModel>(companyDto);
            return View(company);
        }

        // POST: Companies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _companyService.DeleteCompanyAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Labange.PL/Controllers/ResumesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Labange.BLL.DTO.Resume;
using Labange.BLL.Interfaces;
using Labange.PL.Infrastructure.Mappers;
using Labange.PL.Models.Resume;
using Microsoft.AspNetCore.Mvc;

namespace Labange.PL.Controllers
{
    public class ResumesController : Controller
    {
        private const string SortNameDesc = "name_desc";
        private const string SortExperienceYearsAsc = "experienceYears_asc";
        private const string SortExperienceYearsDesc = "experienceYears_desc";
        private const string SortSkillCategoryAsc = "skillCategory_asc";
        private const string SortSkillCategoryDesc = "skillCategory_desc";

        private readonly IResumeService _resumeService;
        private readonly IMapper _mapper;

        public ResumesController(IResumeService resumeService)
        {
            _resumeService = resumeService;
            _mapper = new MapperConfiguration(x => x.AddProfile(new ResumeMapperProfile())).CreateMapper();
        }

        public async Task<IActionResult> Index(string sortOrder)
        {
            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? SortNameDesc : "";
            ViewData["ExperienceYearsSortParm"] = sortOrder == SortExperienceYearsAsc ? SortExperienceYearsDesc : SortExperienceYearsAsc;
            ViewData["SkillCategorySortParm"] = sortOrder == SortSkillCategoryAsc ? SortSkillCategoryDesc : SortSkillCategoryAsc;

            IEnumerable<ResumeListItemDto> resumesDto = await _resumeService.GetAllResumesAsync();
            var resumes = _mapper.Map<IEnumerable<ResumeListItemDto>, IEnumerable<ResumeListItemModel>>(resumesDto);

            switch (sortOrder)
            {
                case SortNameDesc:
                    resumes = resumes.OrderByDescending(r => r.Name);
                    break;
                case SortExperienceYearsAsc:
                    resumes = resumes.OrderBy(r => r.ExperienceYears);
                    break;
                case SortExperienceYearsDesc:
                    resumes = resumes.OrderByDescending(r => r.ExperienceYears);
                    break;
                case SortSkillCategoryAsc:
                    resumes = resumes.OrderBy(r => r.SkillCategory);
                    break;
                case SortSkillCategoryDesc:
                    resumes = resumes.OrderByDescending(r => r.SkillCategory);
                    break;
                default:
                    resumes = resumes.OrderBy(r => r.Name);
                    break;
            }

            return View(resumes);
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            ResumeDetailsDto resumeDto = await _resumeService.GetResumeAsync((int)id);
            var resume = _mapper.Map<ResumeDetailsDto, ResumeDetailsModel>(resumeDto);
            if (resume == null)
            {
                return NotFound();
            }
            return View(resume);
        }

        public async Task<IActionResult> Create(int id)
        {
            bool isExist = await _resumeService.IsExistAsync(id);
            if (isExist)
                return Redirect($"~/Resumes/Details/{id}");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(int id, [Bind("About,ExperienceYears,Skills,PlacesOfWork,SkillCategory")] ResumeCreateModel resumeModel)
        {
            if (ModelState.IsValid)
            {
                resumeModel.UnemployedId = id;
                var resume = _mapper.Map<ResumeCreateModel, ResumeCreateDto>(resumeModel);
                await _resumeService.CreateResumeAsync(resume);
                return RedirectToAction(nameof(Index));
            }

            return View(resumeModel);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            ResumeDetailsDto resumeDto = await _resumeService.GetResumeAsync((int)id);
            var resume = _mapper.Map<ResumeDetailsDto, ResumeDetailsModel>(resumeDto);

            if (resume == null)
            {
                return NotFound();
            }
            return View(resume);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,About,ExperienceYears,Skills,PlacesOfWork,SkillCategory")] ResumeDetailsModel resumeModel)
        {
            if (id != resumeModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                var resume = _mapper.Map<ResumeDetailsModel, ResumeDetailsDto>(resumeModel);
                await _resumeService.UpdateResumeAsync(resume);
                return RedirectToAction(nameof(Index));
            }
            return View(resumeModel);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            ResumeDetailsDto resumeDto = await _resumeService.GetResumeAsync((int)id);
            if (resumeDto == null)
            {
                return NotFound();
            }
            var resume = _mapper.Map<ResumeDetailsDto, ResumeDetailsModel>(resumeDto);
            return View(resume);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _resumeService.DeleteResumeAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Labange.PL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Labange</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>

    <link href="https://fonts.googleapis.com/css?family=Poppins:300" rel="stylesheet">
</head>
<body>
    <nav class="navbar navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Labange</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Companies" asp-action="Index">Companies</a></li>
                    <li><a asp-area="" asp-controller="Unemployeds" asp-action="Index">Unemployeds</a></li>
                    <li><a asp-area="" asp-controller="Vacations" asp-action="Index">Vacations</a></li>
                    <li><a asp-area="" asp-controller="Resumes" asp-action="Index">Resumes</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a asp-area="" asp-controller="Account" asp-action="Logout">Sign Out</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        <div class="content-container">
            @RenderBody()
        </div>
        <hr />
        <footer>
            <p>&copy; 2018 - Labange</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>